- name: demo on conditions
  hosts: localhost
  connection: local

  vars:
    IS_LIVE: true

  tasks:
    - name: check live or not
      ansible.builtin.debug:
        msg: "yes, it is live"
      when: IS_LIVE
