- name: demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "hello {{ item }}"
      loop:
        - ramesh
        - ganesh
        - suresh
