- name: install packages
  hosts: localhost
  connection: local 
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop: 
    - mysql
    - nginx
    - zip
