- name: install packages
  hosts: localhost
  connection: local 
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop: # list of string
    - mysql
    - nginx
    - zip
